# Generated by Django 3.0.6 on 2020-06-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200601_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkinclass',
            options={'ordering': ['student'], 'verbose_name_plural': 'Thời khóa biểu cá nhân'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['classname'], 'verbose_name_plural': 'Lịch học theo lớp'},
        ),
    ]
