# Generated by Django 3.0.6 on 2020-06-01 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200602_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinclass',
            name='classname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Classname'),
        ),
        migrations.AlterField(
            model_name='checkinclass',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Room'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Room'),
        ),
    ]
