# Generated by Django 3.0.6 on 2020-06-02 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200602_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinclass',
            name='daylearn',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày học'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkinclass',
            name='timelearnend',
            field=models.TimeField(blank=True, null=True, verbose_name='Thời gian kết thúc'),
        ),
        migrations.AddField(
            model_name='checkinclass',
            name='timelearnstart',
            field=models.TimeField(blank=True, null=True, verbose_name='Thời gian học'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='daylearn',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày học'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='timelearnend',
            field=models.TimeField(blank=True, null=True, verbose_name='Thời gian kết thúc'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='timelearnstart',
            field=models.TimeField(blank=True, null=True, verbose_name='Thời gian học'),
        ),
    ]
