# Generated by Django 3.0.6 on 2020-06-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200602_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinclass',
            name='id_student',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='ID học viên'),
        ),
    ]
