# Generated by Django 3.0.6 on 2020-06-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_checkinclass_id_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinclass',
            name='id_student',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID học viên'),
        ),
        migrations.AddField(
            model_name='student',
            name='havedetailschedule',
            field=models.BooleanField(default=True, verbose_name='Thời khóa biểu cá nhân'),
        ),
    ]
