# Generated by Django 3.0.6 on 2020-06-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200603_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='id_classname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID học viên'),
        ),
        migrations.AlterField(
            model_name='student',
            name='havedetailschedule',
            field=models.BooleanField(default=False, verbose_name='Thời khóa biểu cá nhân'),
        ),
    ]
