# Generated by Django 3.0.6 on 2020-06-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200606_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinclass',
            name='id_student',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ID học viên'),
        ),
    ]
