# Generated by Django 3.0.6 on 2020-06-06 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200606_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkinclass',
            options={'ordering': ['student'], 'verbose_name_plural': 'Thời khóa biểu cá nhân'},
        ),
    ]
