# Generated by Django 3.0.6 on 2020-06-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200606_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiêu đề')),
                ('content', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nội dung')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('active', models.BooleanField(default=True, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name_plural': 'Thông báo',
                'ordering': ['title'],
            },
        ),
    ]
