# Generated by Django 3.0.6 on 2020-06-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='id_classname',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ID lớp học'),
        ),
    ]
